<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('orders',function(Blueprint $table){$table->id();$table->string('order_no',30)->unique();$table->integer('customer_id')->nullable();$table->unsignedBigInteger('customer_address_id')->nullable();$table->unsignedBigInteger('payment_method_id');$table->string('source',20)->default('website');$table->string('status',30)->default('new');$table->string('customer_name',60);$table->string('customer_surname',60)->nullable();$table->string('customer_mobile',20);$table->string('address_title',50)->nullable();$table->string('city',100);$table->string('district',100)->nullable();$table->string('address',500);$table->string('building',50)->nullable();$table->string('entrance',50)->nullable();$table->string('floor',30)->nullable();$table->string('apartment',30)->nullable();$table->text('address_note')->nullable();$table->boolean('gift_wrap')->default(false);$table->text('customer_note')->nullable();$table->decimal('subtotal',12,2);$table->decimal('discount',12,2)->default(0);$table->decimal('total',12,2);$table->unsignedBigInteger('created_by')->nullable();$table->timestamps();$table->foreign('customer_id')->references('id')->on('customers')->nullOnDelete();$table->foreign('customer_address_id')->references('id')->on('customer_addresses')->nullOnDelete();$table->foreign('payment_method_id')->references('id')->on('payment_methods');});
  Schema::create('order_items',function(Blueprint $table){$table->id();$table->unsignedBigInteger('order_id');$table->unsignedInteger('product_id');$table->unsignedBigInteger('product_variant_id');$table->string('product_name');$table->string('brand_name')->nullable();$table->string('size_name')->nullable();$table->decimal('unit_price',12,2);$table->unsignedInteger('quantity');$table->decimal('total',12,2);$table->timestamps();$table->foreign('order_id')->references('id')->on('orders')->cascadeOnDelete();});
  Schema::create('order_status_logs',function(Blueprint $table){$table->id();$table->unsignedBigInteger('order_id');$table->string('status',30);$table->text('note')->nullable();$table->unsignedBigInteger('user_id')->nullable();$table->timestamps();$table->foreign('order_id')->references('id')->on('orders')->cascadeOnDelete();});
 }
 public function down(): void {Schema::dropIfExists('order_status_logs');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');}
};
